- name: ZSH
  block:
    - name: ZSH - Write .zshrc
      ansible.builtin.copy:
        src: files/zsh/zshrc
        dest: "{{ home }}/.zshrc"

    - name: ZSH - Write powerlevel10k config
      ansible.builtin.copy:
        src: ./files/zsh/p10k.zsh
        dest: "{{ home }}/.p10k.zsh"
  tags:
    - zsh

- name: bat
  block:
    - name: bat - Create config directory
      ansible.builtin.file:
        path: "{{ xdg_config_home }}/bat"
        state: directory
      register: bat_config_dir_result

    - name: bat - Write config
      ansible.builtin.copy:
        src: files/bat/config
        dest: "{{ bat_config_dir_result.path }}/config"
  tags:
    - bat

- name: WezTerm
  block:
    - name: WezTerm - Create config directory
      ansible.builtin.file:
        path: "{{ xdg_config_home }}/wezterm"
        state: directory
      register: wezterm_config_dir_result

    - name: WezTerm - Write config
      ansible.builtin.copy:
        src: files/wezterm/wezterm.lua
        dest: "{{ wezterm_config_dir_result.path }}/wezterm.lua"

    - name: WezTerm - Create colors directory
      ansible.builtin.file:
        path: "{{ wezterm_config_dir_result.path }}/colors"
        state: directory
      register: wezterm_colors_dir_result

    - name: WezTerm - Write colors
      ansible.builtin.copy:
        src: "files/wezterm/colors/{{ item }}.toml"
        dest: "{{ wezterm_colors_dir_result.path }}/{{ item }}.toml"
      loop:
        - dayfox
        - nordfox
  tags:
    - wezterm
