- name: Create directory for Node.js packages
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/node_packages"
    mode: 0755
    state: directory

- name: Install Node.js packages
  community.general.npm:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.local/node_packages"
    production: true
    state: present
  loop: "{{ node_packages }}"
